### ISSUE TITLE
Looks like images stopped publishing

### ISSUE THREAD

**Issue by buzden** [alexhumphreys/idris2-dockerfile#6]
According to [docker's overview](https://hub.docker.com/r/snazzybucket/idris2/tags), 5 days ago images stopped being built regularly, having the last image being built 2 days ago after a pause. Well, I don't know, maybe it's a github's workflow issue, but can you check what's going on?

**Comment by buzden** [comment]
Well, it seems that publishing restored, at least to some extent (it seems to be published not every day, but at least whenever recently), so closing this for now.

**Comment by alexhumphreys** [comment]
Ah sorry, missed this issue. Yeah, think if there's no commits github stops running scheduled jobs after 2 months or so. Actually pretty confused how it started again...

**Comment by buzden** [comment]
Github actions again stopped running the scheduled jobs after 60 days without commits. Could you please enable runs again?

**Comment by buzden** [comment]
Thanks for re-enabling

**Comment by alexhumphreys** [comment]
Hopefully the https://github.com/alexhumphreys/idris2-dockerfile/pull/7 PR will:
1. keep the readme up to date.
2. cause regular commits so that the scheduled jobs don't get disabled.
